import os
import json
import google.generativeai as genai
from __future__ import generator_stop
import cv2
import math

# Load the damage report JSON generated by meg.py
with open("damage_report.json", "r") as f:
    damage_report = json.load(f)

car_model = input("Enter the car model: ")

# Prepare prompt for cost estimation
cost_prompt = f"""
Given the following car model and its damage report, estimate the repair cost for each damage type and the total cost. 
Format the output as a JSON dictionary with damage types as keys and their estimated costs as values, plus a 'total_cost' key.

Car model: {car_model}
Damage report: {json.dumps(damage_report)}

Example output:
{{
  "Front-Windscreen-Damage": 5000,
  "Headlight-Damage": 2000,
  "fender-dent": 1500,
  ...
  "total_cost": 8500
}}
"""

api_key = "your api"
genai.configure(api_key=api_key)
try:
    gen_model = genai.GenerativeModel('gemma-3-4b-it')
    response = gen_model.generate_content(
        cost_prompt,
        generation_config={"temperature": 0.1}
    )
    output_text = response.text.strip()
    if "```json" in output_text:
        json_string = output_text.split("```json")[1].split("```")[0].strip()
    else:
        json_string = output_text
    cost_report = json.loads(json_string)
    print(json.dumps(cost_report, indent=2))
    # Save the cost report to a new file
    with open("cost_report.json", "w") as f:
        json.dump(cost_report, f, indent=2)
except Exception as e:
    print("Error:", e)